import QtQuick 2.0

QtObject
{
    property string heart: "\e900"
    property string cloud: "\e901"
    property string star: "\e902"
    property string tv: "\e903"
    property string sound: "\e904"
    property string video: "\e905"
    property string trash: "\e906"
    property string user: "\e907"
    property string key: "\e908"
    property string search: "\e909"
    property string settings: "\e90a"
    property string camera: "\e90b"
    property string tag: "\e90c"
    property string lock: "\e90d"
    property string bulb: "\e90e"
    property string pen: "\e90f"
    property string diamond: "\e910"
    property string display: "\e911"
    property string location: "\e912"
    property string eye: "\e913"
    property string bubble: "\e914"
    property string stack: "\e915"
    property string cup: "\e916"
    property string phone: "\e917"
    property string news: "\e918"
    property string mail: "\e919"
    property string like: "\e91a"
    property string photo: "\e91b"
    property string note: "\e91c"
    property string clock: "\e91d"
    property string paperplane: "\e91e"
    property string params: "\e91f"
    property string banknote: "\e920"
    property string data: "\e921"
    property string music: "\e922"
    property string megaphone: "\e923"
    property string study: "\e924"
    property string lab: "\e925"
    property string food: "\e926"
    property string t_shirt: "\e927"
    property string fire: "\e928"
    property string clip: "\e929"
    property string shop: "\e92a"
    property string calendar: "\e92b"
    property string wallet: "\e92c"
    property string vynil: "\e92d"
    property string truck: "\e92e"
    property string world: "\e92f"
}
