import QtQuick 2.0

QtObject
{
    property string sunrise: "\e900"
    property string sun: "\e901"
    property string moon: "\e902"
    property string sun2: "\e903"
    property string windy: "\e904"
    property string wind: "\e905"
    property string snowflake: "\e906"
    property string cloudy: "\e907"
    property string cloud: "\e908"
    property string weather: "\e909"
    property string weather2: "\e90a"
    property string weather3: "\e90b"
    property string lines: "\e90c"
    property string cloud2: "\e90d"
    property string lightning: "\e90e"
    property string lightning2: "\e90f"
    property string rainy: "\e910"
    property string rainy2: "\e911"
    property string windy2: "\e912"
    property string windy3: "\e913"
    property string snowy: "\e914"
    property string snowy2: "\e915"
    property string snowy3: "\e916"
    property string weather4: "\e917"
    property string cloudy2: "\e918"
    property string cloud3: "\e919"
    property string lightning3: "\e91a"
    property string sun3: "\e91b"
    property string moon2: "\e91c"
    property string cloudy3: "\e91d"
    property string cloud4: "\e91e"
    property string cloud5: "\e91f"
    property string lightning4: "\e920"
    property string rainy3: "\e921"
    property string rainy4: "\e922"
    property string windy4: "\e923"
    property string windy5: "\e924"
    property string snowy4: "\e925"
    property string snowy5: "\e926"
    property string weather5: "\e927"
    property string cloudy4: "\e928"
    property string lightning5: "\e929"
    property string thermometer: "\e92a"
    property string compass: "\e92b"
    property string none: "\e92c"
    property string celsius: "\e92d"
    property string fahrenheit: "\e92e"
}
